# Generated by Django 4.1.3 on 2023-04-14 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('team_name', models.CharField(blank=True, max_length=200, null=True)),
                ('team_leader_name', models.CharField(blank=True, max_length=200, null=True)),
                ('team_leader_roll', models.CharField(blank=True, max_length=200, null=True)),
                ('member2_name', models.CharField(blank=True, max_length=200, null=True)),
                ('member2_roll', models.CharField(blank=True, max_length=200, null=True)),
                ('member3_name', models.CharField(blank=True, max_length=200, null=True)),
                ('member3_roll', models.CharField(blank=True, max_length=200, null=True)),
                ('dept', models.CharField(blank=True, max_length=30, null=True)),
                ('member1_pic', models.ImageField(upload_to='media/students/')),
                ('member2_pic', models.ImageField(upload_to='media/students/')),
                ('member3_pic', models.ImageField(upload_to='media/students/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualif', models.CharField(blank=True, max_length=200, null=True)),
                ('picture', models.ImageField(upload_to='media/supervisors_images/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(blank=True, null=True)),
                ('rating1', models.IntegerField(blank=True, null=True)),
                ('rating2', models.IntegerField(blank=True, null=True)),
                ('rating3', models.IntegerField(blank=True, null=True)),
                ('rating4', models.IntegerField(blank=True, null=True)),
                ('total_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_project', to='iclick_main_app.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualif', models.CharField(blank=True, max_length=200, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/reviewers_images/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
