# Generated by Django 4.1.3 on 2023-04-14 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iclick_main_app', '0002_projectdetails_supervisor_reviews_reviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(blank=True, null=True)),
                ('rating1', models.IntegerField(blank=True, null=True)),
                ('rating2', models.IntegerField(blank=True, null=True)),
                ('rating3', models.IntegerField(blank=True, null=True)),
                ('rating4', models.IntegerField(blank=True, null=True)),
                ('total_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='SupervisorDetails',
            new_name='Supervisor',
        ),
        migrations.RenameModel(
            old_name='ProjectDetails',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='ReviewerDetails',
            new_name='Reviewer',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.AddField(
            model_name='project_reviews',
            name='project_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iclick_main_app.project'),
        ),
        migrations.AddField(
            model_name='project_reviews',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iclick_main_app.reviewer'),
        ),
    ]
