# Generated by Django 4.1.3 on 2023-04-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iclick_main_app', '0003_project_reviews_rename_supervisordetails_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rating_review',
            field=models.ManyToManyField(default=list, to='iclick_main_app.project_reviews'),
        ),
    ]
