# Generated by Django 4.1.3 on 2023-04-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iclick_main_app', '0004_project_rating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/projects_img/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='member1_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/students/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='member2_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/students/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='member3_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/students/'),
        ),
    ]
