# Generated by Django 4.1.3 on 2023-04-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iclick_main_app', '0005_project_featured_image_alter_project_member1_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rating_review',
            field=models.ManyToManyField(default=None, to='iclick_main_app.project_reviews'),
        ),
    ]
