# Generated by Django 4.1.3 on 2023-04-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iclick_main_app', '0006_alter_project_rating_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rating_review',
            field=models.ManyToManyField(blank=True, default=None, to='iclick_main_app.project_reviews'),
        ),
    ]
